name: install-netlify-package
on: [push]
jobs:
  check-netlify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
      - run: npm install netlify-cli -g
      - run: npm netlify -v 
  
